config/routes.rb
Rails.application.routes.draw do

root 'sessions#new'

   get 'signup' => 'victims#new', as: :sign_up
   post  'signup' => 'victims#create'
  
   get 'signin' => 'sessions#new', as: :sign_in
   post 'signin' => 'sessions#create'
   delete 'signout' => 'sessions#delete', as: :sign_out
  
   resources :sessions, only: [:create]

   get 'shelters/' => 'shelters#index'

   get 'shelters/new' => 'shelters#new'

   post 'shelters' => 'shelters#create'

   get 'shelters/:id' => 'shelters#show', as: :shelter

   get 'victims/:id/edit' => 'victims#edit'

   get 'shelters/edit' => 'shelters#edit'

   patch 'shelters/update' => 'shelters#update'

   delete 'shelters/destroy'

   delete 'victims/:id' => 'victims#destroy'

   get 'zshelters' => 'signups#index', as: :zshelters

   get 'zshelters/new' => 'signups#new', as: :new_zshelter

   post 'zshelters' => 'signups#create'

   get 'zshelters/:id' => 'signups#show', as: :zshelter

  resources :victims
  resources :shelters
 

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
	has_many :signups
	has_many :victims, through: :signups
	
end

app/models/signup.rb
class Signup < ActiveRecord::Base
belongs_to :shelter
belongs_to :victim

end

app/models/victim.rb
class Victim < ActiveRecord::Base

has_many :signups
has_many :shelters, through: :signups



VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	before_save {self.email = email.downcase}
	
	validates :email, presence: :true,
				format: {with: VALID_EMAIL_REGEX},
				uniqueness: {case_sensitive: false}

	validates :password, length: {minimum: 6}

	before_create :create_remember_token
	has_secure_password
	
	def Victim.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def Victim.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
	def create_remember_token
		self.remember_token = Victim.digest(Victim.new_remember_token)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if signed_in?
			redirect_to current_victim
		end	
	end		

	def create
		victim = Victim.find_by(email: params[:session][:email].downcase)
		if victim && victim.authenticate(params[:session][:password])
			sign_in victim
			redirect_to victim
		else
			render 'new'
		end		
	end	
	
	def delete
		sign_out
		redirect_to root_url
	end	


end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

def index
	@shelters = Shelter.all 
end
def new
	@shelter = Shelter.new
end	

def create 
	@shelter = Shelter.new(shelter_params)
	if @shelter.save
		@shelters = Shelter.all
		render action: 'index'
	else
		render action: 'new'
	end	
end

def show
	@shelter = Shelter.find(params[:id])
end

def edit
	@shelter = Shelter.find(params[:id])
end	

def update
	 @shelter = Shelter.find(params[:id])
    if @shelter.update_attributes(shelter_params)
     redirect_to(@shelter)   
    else
      render action: 'edit'
    end
end	

def destroy
	@shelter = Shelter.find(params[:id])
    @shelter.destroy
    redirect_to shelters_path
 end

private
	def shelter_params
		params.require(:shelter).permit(:name, :city, :zip, :contact_phone, :contact_email)
	end	
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

def index
	@zshelters = Signup.all
end



def new
	@signup = Signup.new
	@shelter_id = params[:format]
	@victim_id = current_victim.id
end


def show
	@signup = Signup.new
end


def create
	@signup = Signup.new(signup_params)

	if @signup.save
		@signups = Signup.all
		redirect_to @signup
	else
		render 'new'
	end
end


private
	def signup_params
		params.require(:signup).permit(:shelter_id, :victim_id)
	end

end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
   before_action :find_victim, only: [:show, :edit, :update, :destroy]
    before_action :signed_in_victim, except: [:new, :create]
    before_action :correct_victim, except: [:new, :create] 
	
def index
		@victims = Victim.all
end

def new

  if current_victim
      redirect_to current_victim
  else 
      @victim = Victim.new
  end
  
end

def create
    @victim = Victim.new(victim_params)

  if @victim.save
    sign_in @victim
     @victims = Victim.all
      redirect_to @victim
  else
      render action: 'new'
  end
end

def edit
    @victim = Victim.find(params[:id])
end


def update
      respond_to do |format|
    if @victim.update(victim_params)
          format.html { redirect_to @victim, notice: 'Victim was successfully updated.' }
          format.json { render :show, status: :ok, location: @victim }
    else
          format.html { render :edit }
          format.json { render json: @victim.errors, status: :unprocessable_entity }
    end
  end
end


  def show
      @victim = Victim.find(params[:id])
  end



  def destroy
    @victim = Victim.find(params[:id])
    @victim.destroy
    redirect_to root_path
  end



private
    def victim_params
      params.require(:victim).permit(:name, :email, :password, :password_confirmation)
    end

    def find_victim
      @victim = Victim.find(params[:id])
    end

    def correct_victim
      find_victim
      redirect_to(current_victim) unless current_victim?(@victim)
    end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


	def sign_in(victim)
		remember_token = Victim.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		victim.update_attribute(:remember_token, Victim.digest(remember_token))
		self.current_victim = victim
	end
	
	def signed_in_victim
		unless signed_in?
		redirect_to root_url, notice: "Please sign in."	
		end
	end
	
	def signed_in?
		!current_victim.nil?
	end	

	def current_victim=(victim)
		@current_victim = victim
	end



	def current_victim
		remember_token = Victim.digest(cookies[:remember_token])
		@current_victim ||= Victim.find_by(remember_token: remember_token)
	end
	
	def correct_victim
		@victim = Victim.find(params[:id])
		redirect_to(root_url) unless current_victim?(@victim)	
	end

	def current_victim?(victim)
		victim == current_victim
	end
	
	def sign_out
		current_victim.update_attribute(:remember_token, Victim.digest(Victim.new_remember_token))
		cookies.delete(:remember_token)
		self.current_victim = nil
	end		



end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DomViolenceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        
    
        <a class="navbar-brand" href="/shelters">Breaking Free</a>
        <ul class="nav navbar-right">
        <li><div><%= link_to "Sign out", sign_out_path, method: "delete", class: "btn btn-primary navbar-btn" %></div></li>
        <ul> 
      </nav>
    </div>
  </div>
 </header>  

</head>
<body>

<%= yield %>

</body>
</html>

app/views/shelters/edit.html.erb
<%= form_for(@shelter) do |f| %>
<div class="formTile">
	<div class="form-group">
    <h1>Edit Shelter</h1>
	<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
	<%= f.text_field :city , placeholder: "City", class: "form-control"  %>
	<%= f.text_field :contact_phone , placeholder: "Contact Phone", class: "form-control" %>
	<%= f.text_field :contact_email , placeholder: "Contact Email", class: "form-control" %>
	<%= link_to 'Back', shelters_path , :class => "btn btn-primary" %>
	<%=  f.submit class: "btn btn-success" %>
	<%= link_to 'Delete', @shelter, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger" %>
    </div>
</div>
		
	    

<% end %>

app/views/shelters/index.html.erb
	<div>
    <h1 id="sheltEdit">Shelters Near You</h1>
	</div>
	
	
	
<% @shelters.each do |shelter| %>
	<%= link_to shelter do %>
	<div class="eventTile">
		
		<%= shelter.name %><br/>
		<%= shelter.city %><br/>
		<%= shelter.contact_phone %><br/>
		<%= shelter.zip %><br/>
		
	</div>
		
	<% end %>
			
			

			

	<% end %>

app/views/shelters/new.html.erb
	
		
<%= form_for(@shelter) do |f| %>
	<div class="formTile">
	   <div class="form-group">
		<h1>Add New Shelter</h1>
		<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
		<%= f.text_field :city , placeholder: "City", class: "form-control" %>
		<%= f.text_field :zip , placeholder: "Zipcode", class: "form-control" %>
		<%= f.text_field :contact_phone , placeholder: "Contact Phone", class: "form-control" %>
		<%= f.text_field :contact_email , placeholder: "Contact Email", class: "form-control" %>
		<%= link_to 'Back', shelters_path , :class => "btn btn-primary" %>
		<%=  f.submit class: "btn btn-success" %>
	   </div>
	</div>	
		
	    

	        <% end %>

app/views/shelters/show.html.erb
	<div class="formTile">
      <h1><%= @shelter.name %></h1>
  	  <p><%= @shelter.city %></p>
      <p><%= @shelter.zip %></p>
      <p><%= @shelter.contact_phone %></p>
      <p><%= @shelter.contact_email %></p>
       <%= link_to 'Back', shelters_path, :class => "btn btn-primary" %>
       <%= link_to 'Edit', edit_shelter_path, :class => "btn btn-warning" %>
       <%= link_to 'Choose this shelter', new_zshelter_path(@shelter), :class => "btn btn-success" %>
     </div>  
      
      
 

app/views/shelters/update.html.erb
<h1>Shelters#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/signups/index.html.erb
<h1>Here are the shelters for you</h1>
	
	<% @zshelters.each do |zshelter| %>
		<%= link_to zshelter do %>
			<div>
				<p><%= Shelter.find(zshelter.shelter_id).name %> </p>

			</div>
		<% end %>	
	<% end %>
</div>

app/views/signups/new.html.erb
<%= form_for(@signup, url: zshelters_path) do |f| %>


<%= f.hidden_field :victim_id, :value => @victim_id %>
<%= f.hidden_field :shelter_id, :value => @shelter_id %>

<%= f.submit "Confirm for shelter", class: "btn btn-large btn-primary" %>

<% end %>

app/views/signups/show.html.erb
<h1>Here are the shelters for you</h1>
	
	<% @zshelters.each do |zshelter| %>
		<%= link_to zshelter do %>
			<div>
				<p><%= Shelter.find(zshelter.shelter_id).name %> </p>

			</div>
		<% end %>	
	<% end %>
</div>

app/views/victims/edit.html.erb
<%= form_for(@victim) do |f| %>
<div class="formTile">
	<div class="form-group">
		<h2>Edit Your Account</h2>
		<%= f.text_field :name, placeholder: 'Update Name' , class: "form-control" %>
		<%= f.text_field :email, placeholder: 'Update Email', class: "form-control"%>
			<%= f.text_field :password, placeholder: 'Update Password', class: "form-control"%>
	<%= f.text_field :password_confirmation, placeholder: 'Confirm New Password', class: "form-control"%>
	</div>
	<%=f.submit class: "btn btn-success" %>

	<%= link_to 'Delete Your Account', @victim, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger" %>
</div>

<% end %>

app/views/victims/index.html.erb
<h1>Victim's Page</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @victims.each do |victim| %>
      <tr>
        <td><%= victim.name %></td>
        <td><%= victim.email %></td>
        <td><%= victim.remember_token %></td>
        <td><%= link_to 'Show', victim %></td>
        <td><%= link_to 'Edit', edit_victim_path(victim) %></td>
        <td><%= link_to 'Destroy', victim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Victim', new_victim_path %>

app/views/victims/new.html.erb
  <div class="formTile">
    <div class="form-group">
        <h1>Are You A New Client? </h1>

          
            <%= form_for(@victim) do |f| %>

			  <% if @victim.errors.any? %>
			    <div class="class2" id="error_explanation">
			      <%= pluralize(@victim.errors.count, "error") %> prohibited this victim from being saved:
			      <ul>
			        <% @victim.errors.full_messages.each do |message| %>
			        <li class="class3"><%= message %></li>
			        <% end %>
			      </ul>
			    </div>
			  <% end %>
				<%= f.text_field :name, placeholder: 'Name', class: "form-control"%>
				<%= f.text_field :email, placeholder: 'Email', class: "form-control"%>
				<%= f.text_field :password, placeholder: 'Password', class: "form-control"%>
				<%= f.text_field :password_confirmation, placeholder: 'Confirm Password', class: "form-control"%>
				<%= f.submit "Create Account", class: "btn btn-info" %>
				<% end %>
    </div>
  </div>

app/views/victims/show.html.erb
<div class="formTile">
<h2>Thank you <%= @victim.name %>! We want to help to keep you safe, </h2>
<%= link_to "Your Shelters", zshelter_path, class: "btn btn-primary" %>
<%= link_to "Choose a Shelter", shelters_path, class: "btn btn-info" %>
<%= link_to 'Edit Your Profile', edit_victim_path, class: "btn btn-warning" %><br/> 
<%= link_to 'Delete Your Account', @victim, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div> 